# Generated by Django 5.1.1 on 2024-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="post_images")),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("POR", "Portrait"),
                            ("LAN", "Landscape"),
                            ("SQU", "Square"),
                            ("NSP", "Not Specified"),
                        ],
                        default="NSP",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Artwork",
                "verbose_name_plural": "Artworks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("is_censored", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_favorite", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
            },
        ),
    ]
