# Generated by Django 5.1.1 on 2024-09-25 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="artwork",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.artwork"),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[("ART", "Artist"), ("AUD", "Audience"), ("BOT", "Both")], default="AUD", max_length=3
                    ),
                ),
                ("profile_picture", models.ImageField(upload_to="profiles")),
                ("bio", models.TextField()),
                ("location", models.CharField(max_length=30)),
                ("websites", models.JSONField(default=dict, help_text="Websites associated with the user.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "comments",
                    models.ManyToManyField(related_name="commented_by", through="core.Comment", to="core.artwork"),
                ),
                (
                    "following",
                    models.ManyToManyField(related_name="followed", through="core.Follow", to="core.profile"),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.AddField(
            model_name="follow",
            name="followed_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="follow_to", to="core.profile"
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="following_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="follow_by", to="core.profile"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="profile",
            field=models.ForeignKey(
                help_text="The profile of the commenter.",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="profile",
            field=models.ForeignKey(
                help_text="The profile of the artist.", on_delete=django.db.models.deletion.CASCADE, to="core.profile"
            ),
        ),
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(choices=[("LIK", "Like"), ("DIS", "Dislike")], default="LIK", max_length=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="artwork_sentiment", to="core.artwork"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile_sentiment", to="core.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sentiment",
                "verbose_name_plural": "Sentiments",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="sentiment",
            field=models.ManyToManyField(related_name="sentiment_by", through="core.Sentiment", to="core.artwork"),
        ),
        migrations.CreateModel(
            name="View",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("artwork", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.artwork")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.profile")),
            ],
            options={
                "verbose_name": "View",
                "verbose_name_plural": "Views",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="views",
            field=models.ManyToManyField(related_name="viewed_by", through="core.View", to="core.artwork"),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("following_profile", "followed_profile"), name="unique_following"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["created_at"], name="core_commen_created_97080c_idx"),
        ),
        migrations.AddConstraint(
            model_name="artwork",
            constraint=models.UniqueConstraint(fields=("profile", "title"), name="unique_artwork"),
        ),
        migrations.AddConstraint(
            model_name="sentiment",
            constraint=models.UniqueConstraint(fields=("profile", "artwork"), name="unique_sentiment"),
        ),
        migrations.AddConstraint(
            model_name="view",
            constraint=models.UniqueConstraint(fields=("profile", "artwork"), name="unique_view"),
        ),
    ]
