# Generated by Django 5.1.1 on 2024-09-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="profiles"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="websites",
            field=models.JSONField(blank=True, default=dict, help_text="Websites associated with the user."),
        ),
    ]
