# Generated by Django 5.1.1 on 2024-09-26 11:43

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Profile = apps.get_model("core", "Profile")
    for row in Profile.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    Comment = apps.get_model("core", "Comment")
    for row in Comment.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

    Artwork = apps.get_model("core", "Artwork")
    for row in Artwork.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20240926_1143"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
