# Generated by Django 5.1.1 on 2024-09-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraccount",
            options={},
        ),
        migrations.AlterModelManagers(
            name="useraccount",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="username",
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
