# Generated by Django 5.1.1 on 2024-09-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_useraccount_options_alter_useraccount_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="name",
            field=models.CharField(default="None", max_length=255),
        ),
    ]
