# Generated by Django 5.1.1 on 2024-09-26 11:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_useraccount_date_joined_useraccount_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
