# Generated by Django 5.1.1 on 2024-09-26 11:43

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    """Generate UUIDs for existing UserAccounts."""
    UserAccount = apps.get_model("users", "UserAccount")
    Profile = apps.get_model("core", "Profile")
    for row in UserAccount.objects.all():
        # Create a Profile for this UserAccount if it doesn't exist
        if not getattr(row, "profile", None):
            Profile.objects.create(account=row)

        # If the associated profile has a uuid, make this user's uuid the same
        if getattr(row.profile, "uuid", None):
            print(f"Setting {row} uuid to {row.profile.uuid}")
            row.uuid = row.profile.uuid
        else:
            print(f"Setting {row} uuid to uuid.uuid4()")
            row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_auto_20240926_1143"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
