# Generated by Django 5.1.1 on 2024-09-26 11:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20240926_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
